// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicStreamer.Infrastructure.EntityFrameworkProvider.Context;

#nullable disable

namespace MusicStreamer.Infrastructure.EntityFrameworkProvider.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250623133816_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BandaUsuario", b =>
                {
                    b.Property<Guid>("BandasFavoritasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FavoritadaPorUsuariosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BandasFavoritasId", "FavoritadaPorUsuariosId");

                    b.HasIndex("FavoritadaPorUsuariosId");

                    b.ToTable("UsuariosBandasFavoritas", (string)null);
                });

            modelBuilder.Entity("MusicStreamer.Domain.Entities.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAssinatura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Assinaturas", (string)null);
                });

            modelBuilder.Entity("MusicStreamer.Domain.Entities.Banda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bandas", (string)null);
                });

            modelBuilder.Entity("MusicStreamer.Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Autorizada")
                        .HasColumnType("bit");

                    b.Property<string>("Comerciante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoNegacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("MusicStreamer.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Musica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BandaId");

                    b.ToTable("Musicas", (string)null);
                });

            modelBuilder.Entity("MusicaUsuario", b =>
                {
                    b.Property<Guid>("FavoritadaPorUsuariosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicasFavoritasId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FavoritadaPorUsuariosId", "MusicasFavoritasId");

                    b.HasIndex("MusicasFavoritasId");

                    b.ToTable("UsuariosMusicasFavoritas", (string)null);
                });

            modelBuilder.Entity("BandaUsuario", b =>
                {
                    b.HasOne("MusicStreamer.Domain.Entities.Banda", null)
                        .WithMany()
                        .HasForeignKey("BandasFavoritasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStreamer.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("FavoritadaPorUsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicStreamer.Domain.Entities.Assinatura", b =>
                {
                    b.HasOne("MusicStreamer.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Assinatura")
                        .HasForeignKey("MusicStreamer.Domain.Entities.Assinatura", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MusicStreamer.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("MusicStreamer.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Transacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Musica", b =>
                {
                    b.HasOne("MusicStreamer.Domain.Entities.Banda", "Banda")
                        .WithMany("Musicas")
                        .HasForeignKey("BandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banda");
                });

            modelBuilder.Entity("MusicaUsuario", b =>
                {
                    b.HasOne("MusicStreamer.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("FavoritadaPorUsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musica", null)
                        .WithMany()
                        .HasForeignKey("MusicasFavoritasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicStreamer.Domain.Entities.Banda", b =>
                {
                    b.Navigation("Musicas");
                });

            modelBuilder.Entity("MusicStreamer.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Assinatura");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
